name: ClaimsProject
version: '0.1-DEV'
main: me.thatsatim.claimsProject.ClaimsProject
api-version: '1.21'
commands:
  claim:
    description: claim a chunk
  unclaim:
    description: unclaim a chunk
  transfer:
    description: transfer a claimed chunk